
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ILHAM
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jDialog1 = new javax.swing.JDialog();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jam = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        nol_jam = new javax.swing.JLabel();
        nol_menit = new javax.swing.JLabel();
        nol_detik = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Nis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Kelas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Cewe = new javax.swing.JRadioButton();
        Cowo = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Alamat = new javax.swing.JTextArea();
        Tanggal = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        Tempat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Data = new javax.swing.JTable();

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Nama");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 450, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("The Real Informatic Schools");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 140, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 0);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORM BIODATA SISWA SMK TELKOM");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 10, 480, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("The Real Informatic School");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 50, 150, 20);

        jam.setText("jam");
        jPanel2.add(jam);
        jam.setBounds(570, 10, 40, 30);

        tanggal.setText("tanggal");
        jPanel2.add(tanggal);
        tanggal.setBounds(570, 40, 40, 30);
        jPanel2.add(labeljam);
        labeljam.setBounds(600, 10, 20, 30);
        jPanel2.add(labeltanggal);
        labeltanggal.setBounds(650, 10, 40, 30);
        jPanel2.add(nol_jam);
        nol_jam.setBounds(720, 40, 0, 30);
        jPanel2.add(nol_menit);
        nol_menit.setBounds(700, 10, 40, 30);
        jPanel2.add(nol_detik);
        nol_detik.setBounds(820, 40, 0, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 80);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("NIS");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(10, 50, 100, 30);
        jPanel3.add(Nis);
        Nis.setBounds(10, 80, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Isian Data Siswa");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(10, 10, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(10, 320, 100, 30);
        jPanel3.add(Nama);
        Nama.setBounds(10, 150, 180, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Kelas");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(10, 380, 100, 30);
        jPanel3.add(Kelas);
        Kelas.setBounds(10, 410, 180, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Alamat");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(10, 510, 100, 30);
        jPanel3.add(Email);
        Email.setBounds(10, 470, 180, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Tanggal Lahir");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 260, 100, 30);

        buttonGroup1.add(Cewe);
        Cewe.setText("Perempuan");
        Cewe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CeweActionPerformed(evt);
            }
        });
        jPanel3.add(Cewe);
        Cewe.setBounds(100, 350, 90, 23);

        buttonGroup1.add(Cowo);
        Cowo.setText("Laki - Laki");
        Cowo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CowoActionPerformed(evt);
            }
        });
        jPanel3.add(Cowo);
        Cowo.setBounds(10, 350, 80, 23);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Email");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 440, 100, 30);

        Alamat.setColumns(20);
        Alamat.setRows(5);
        jScrollPane1.setViewportView(Alamat);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 540, 180, 110);
        jPanel3.add(Tanggal);
        Tanggal.setBounds(10, 290, 180, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Nama");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 120, 100, 30);
        jPanel3.add(Tempat);
        Tempat.setBounds(10, 220, 180, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Tempat");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 190, 100, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(10, 90, 230, 670);

        jPanel4.setBackground(new java.awt.Color(102, 255, 102));
        jPanel4.setLayout(null);

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(20, 20, 80, 30);

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);
        jButton3.setBounds(120, 20, 80, 30);

        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton4);
        jButton4.setBounds(220, 20, 80, 30);

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(320, 20, 80, 30);

        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6);
        jButton6.setBounds(420, 20, 80, 30);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(520, 20, 55, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(250, 90, 620, 70);

        jPanel5.setBackground(new java.awt.Color(102, 255, 102));
        jPanel5.setLayout(null);

        Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis Kelamin", "Kelas", "Email", "Alamat", "Tempat", "Tanggal"
            }
        ));
        Data.setToolTipText("");
        Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Data);

        jPanel5.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 600, 570);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(250, 170, 620, 590);

        setBounds(0, 0, 889, 811);
    }// </editor-fold>//GEN-END:initComponents

    private void CeweActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CeweActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CeweActionPerformed

    private void CowoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CowoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CowoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        String JK = "";
        
        if(Cowo.isSelected()){
            JK = "L";}
        else{
            JK = "P";}
        
        if("".equals(Nis.getText())|| "".equals(Nama.getText())|| "".equals(Kelas.getText())|| "".equals(Email.getText())|| "".equals(Alamat.getText())|| JK.equals("")|| "".equals(Tempat.getText())|| tanggal.equals(""))
        { 
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);}
        else {
                String SQL = "INSERT INTO t_siswa VALUES"
                        + "('"+Nis.getText()+"','"+Nama.getText()+"','"+tanggal+"','"+JK+"',"+"'"+Kelas.getText()+"','"+Email.getText()+"','"+Alamat.getText()+"','"+Tempat.getText()+"','"+tanggal+"')";
                int status = KoneksiDB.execute(SQL);
                if (status == 1){
                JOptionPane.showMessageDialog(this, "Data Berhasil Di Tambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();}
                else{
                JOptionPane.showMessageDialog(this, "Data Gagal Ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
                }
                    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int baris = Data.getSelectedRow();
        if (baris != -1){
        String NIS = Data.getValueAt(baris, 0).toString();
        String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
        int status = KoneksiDB.execute(SQL);
        if(status==1){
        JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
        }else{
        JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal", JOptionPane.WARNING_MESSAGE);}}
        else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Nama.setText("");
        Nis.setText("");
        Kelas.setText("");
        Email.setText("");
        Alamat.setText("");
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DataMouseClicked
        // TODO add your handling code here:
        try{
            int row = Data.rowAtPoint(evt.getPoint());
            
            String nis  = Data.getValueAt(row, 0).toString();
            String nama  = Data.getValueAt(row, 1).toString();
            String kelas  = Data.getValueAt(row, 3).toString();
            String email = Data.getValueAt(row, 4).toString();
            String alamat  = Data.getValueAt(row, 5).toString();
            String tempat   = Data.getValueAt(row, 6).toString();
            String tanggal  = Data.getValueAt(row, 7).toString();
            
            if("Laki-Laki".equals(Data.getValueAt(row, 2).toString())){
                Cowo.setSelected(true);
            }else{
                Cewe.setSelected(true);
            }
            
            Nis.setText(String.valueOf(nis));
            Nama.setText(String.valueOf(nama));
            Kelas.setText(String.valueOf(kelas));
            Email.setText(String.valueOf(email));
            Alamat.setText(String.valueOf(alamat));
            Tempat.setText(String.valueOf(tempat));
            Tanggal.setDate(dateValue);
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_DataMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        
        if("".equals(Nis.getText())|| "".equals(Alamat.getText())||"".equals(Kelas.getText())||"".equals(Nama.getText())||"".equals(Email.getText())|| 
                "".equals(Tempat.getText())||tanggal.equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);          
        }else{
            String JK = "";
            if(Cowo.isSelected()){
                JK = "L";
            }else{
                JK = "P";
            }
            String SQL = "UPDATE t_siswa SET "
                    +"WHERE NamaSiswa='"+Nama.getText()+"',"+"WHERE JenisKelamin='"+JK+"',"
                    +"WHERE Kelas='"+"',"+Kelas.getText()+"',"+"WHERE Email='"+Email.getText()+"',"
                    +"WHERE Alamat='"+"',"+Alamat.getText()+"',"
                    +"WHERE NIS='"+"',"+Nis.getText()+"',"
                    +"WHERE Tempat='"+"',"+Tempat.getText()+"',"
                    +"WHERE Tanggal='"+"',"+tanggal;
            int status = KoneksiDB.execute(SQL);
            if(status == 0){
                JOptionPane.showMessageDialog(this, "Data Berhasil di Update","Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal diUpdate","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    public void setTanggal(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        tanggal.setText(kal.format(skrg));
    }
    
    public void SetJam(){
    ActionListener taskPerformed = new ActionListener() {
        public void actionPerformed(ActionEvent evt){
        Date dt = new Date();
        String nol_jam = null;
        String nol_menit = null;
        String nol_detik = null;
        int nilai_jam = dt.getHours();
        int nilai_menit = dt.getMinutes();
        int nilai_detik = dt.getSeconds();
        if(nilai_jam <= 9){
            nol_jam = "0";
        }
        if (nilai_menit <- 9){
            nol_menit = "0";
        }
        if(nilai_detik <= 9){
            nol_detik = "0";
        }
        
        String jam = nol_jam + Integer.toString(nilai_jam);
        String menit = nol_menit  + Integer.toString(nilai_menit);
        String detik = nol_detik + Integer.toString(nilai_detik);
        labeljam.setText("Jam "+jam + ","+ menit + ","+detik);
    }
    };
    new Timer(100, taskPerformed).start();
            }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Biodata siswa Smk Telkom Malang");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try{
        Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true,null);
        }catch(java.awt.print.PrinterException e){
            System.err.format("cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void selectData() {
        String kolom[] = {"NIS","NamaSiswa","JenisKelamin","Kelas","Email","Alamat","Tempat","Tanggal"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM t_siswa";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while (rs.next()){
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String JenisKelamin = "";
                if("L".equals(rs.getString(3))){
                    JenisKelamin = "Laki-Laki";
                }else{
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(4);
                String Email = rs.getString(5);
                String Alamat = rs.getString(6);
                String Tempat = rs.getString(7);
                String Tanggal  = rs.getString(8);
                String data[] = {NIS,NamaSiswa,JenisKelamin,Kelas,Email,Alamat,Tempat,Tanggal};
                dtm.addRow(data);
            }
        }catch(SQLException ex){
            Logger.getLogger(frame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        Data.setModel(dtm);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Alamat;
    private javax.swing.JRadioButton Cewe;
    private javax.swing.JRadioButton Cowo;
    private javax.swing.JTable Data;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Kelas;
    private javax.swing.JTextField Nama;
    private javax.swing.JTextField Nis;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JTextField Tempat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel jam;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JLabel nol_detik;
    private javax.swing.JLabel nol_jam;
    private javax.swing.JLabel nol_menit;
    private javax.swing.JLabel tanggal;
    // End of variables declaration//GEN-END:variables

    
}
